x-airflow-common:
  &airflow-common
  image: apache/airflow:2.9.1-python3.12
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@khamis-postgres:5432/airflow
    AIRFLOW__WEBSERVER__DEFAULT_USER_USERNAME: admin
    AIRFLOW__WEBSERVER__DEFAULT_USER_PASSWORD: admin
  volumes:
    - ./dags:/opt/airflow/dags
    - ./data:/opt/airflow/data
    - ./requirements.txt:/requirements.txt
  depends_on:
    khamis-postgres:
      condition: service_healthy

services:
  khamis-postgres:
    container_name: khamis-postgres
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  khamis-webserver:
    <<: *airflow-common
    container_name: khamis-webserver
    command: webserver
    ports:
      - "8080:8080"

  khamis-scheduler:
    <<: *airflow-common
    container_name: khamis-scheduler
    command: scheduler

  khamis-init:
    <<: *airflow-common
    container_name: khamis-init
    entrypoint: >
      /bin/bash -c "
      pip install --no-cache-dir -r /requirements.txt &&
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname Khamis --lastname Airflow --role Admin --email admin@example.com
      "

volumes:
  postgres-db-volume:
